### PR TITLE
Defaults, actorId, createList

### PR DESCRIPTION
**Pull request by Larkinabout**
- Defaults: Add Abilities, Combat and Skills subcategories to defaults.
- actorId: Add actorId to encodedValue for getActor in RollHandler.
- createList: Remove system subcategory as made available via defaults.
image

### CODE REVIEW

**Comment by Larkinabout** [comment]
A point on the Abilities and Skills derived subcategories: if the sorting groups are fixed, I would suggest adding them as system subcategories instead for the user to choose from; as well as putting them in the default HUD layout. This will let the user pick and choose what sortings they want to show on the HUD and also removes the additional 'Skills' subtitle (although this can be hidden by the user with the 'Show Title' option in the context dialog.

**Comment by farling42** [comment]
Unfortunately, within the game system the four categories of skills and four categories of abilities can have a different name on each Actor - although there will only ever be a maximum of 4 groups, but some might be empty (and thus don't want the subheading to be displayed).

**Comment by farling42** [comment]
Is it right that even with no token selected, I still see the title of an Actor?

**Comment by Larkinabout** [comment]
> Is it right that even with no token selected, I still see the title of an Actor?

If you don't have a character assigned to the user, the HUD should disappear completely with no token selected. It seems to be working okay on my fork of this module.

**Comment by farling42** [comment]
I'm still getting the label shown when no token is selected as a GM.
Your patch doesn't seem to have made any difference since the action HUD buttons are still not appearing.
There's no debug that might indicate what is wrong, although in the `addActionsToActionList` routine, the value of `const subcategories` is a zero-length array, which doesn't seem correct.
In the same routine, this.categoryManager has an empty array for categories[]:
image

**Comment by farling42** [comment]
Ah, when I selected the "Reset HUD" button, and did save changes, then the HUD started working.

It must be saving data, even when there is bad data.

**Comment by farling42** [comment]
When no token is selected, then the HUD is reverting back to one particular actor's token every time.

**Comment by farling42** [comment]
> When no token is selected, then the HUD is reverting back to one particular actor's token every time.

Ok, my issue - the GM had a player assigned as a default character (the actor name didn't appear in the user list though).

**Comment by Larkinabout** [comment]
> Ah, when I selected the "Reset HUD" button, and did save changes, then the HUD started working.
> 
> It must be saving data, even when there is bad data.

Yeah, there's not really any checks for bad data, so resetting the HUD when you've fixed something in development is usually the best bet. By the time you're ready for release there hopefully won't be any way for the user to create bad data, so it'll just be migration scripts if any drastic changes need to happen between versions.

**Comment by farling42** [comment]
I've finally fixed a problem with the release action not working, so it should be available for direct download, and I've submitted the package for inclusion in the foundryvtt web site.

I must say that the dnd5e implementation isn't easy to understand if you're really only trying to get it to work for a simple game system :-)

**Pull request merged**
